{{/*
MIT License

(C) Copyright 2022 Hewlett Packard Enterprise Development LP

Permission is hereby granted, free of charge, to any person obtaining a
copy of this software and associated documentation files (the "Software"),
to deal in the Software without restriction, including without limitation
the rights to use, copy, modify, merge, publish, distribute, sublicense,
and/or sell copies of the Software, and to permit persons to whom the
Software is furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included
in all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL
THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR
OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE,
ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
OTHER DEALINGS IN THE SOFTWARE.
*/}}
---
apiVersion: v1
kind: Service
metadata:
  name: tapms-webhook-service
  namespace: {{ .Release.Namespace }}
spec:
  ports:
  - port: 443
    targetPort: 9443
  selector:
    hpe-operator: cray-tapms
---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: tapms-mutating-webhook-configuration
  annotations:
    cert-manager.io/inject-ca-from: {{ .Release.Namespace }}/tapms-webhook-server-cert
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: tapms-webhook-service
      namespace: {{ .Release.Namespace }}
      path: /mutate-tapms-hpe-com-v1alpha1-tenant
  failurePolicy: Fail
  name: mtenant.kb.io
  rules:
  - apiGroups:
    - tapms.hpe.com
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - tenants
  sideEffects: None
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: tapms-validating-webhook-configuration
  annotations:
    cert-manager.io/inject-ca-from: {{ .Release.Namespace }}/tapms-webhook-server-cert
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: tapms-webhook-service
      namespace: {{ .Release.Namespace }}
      path: /validate-tapms-hpe-com-v1alpha1-tenant
  failurePolicy: Fail
  name: vtenant.kb.io
  rules:
  - apiGroups:
    - tapms.hpe.com
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - tenants
  sideEffects: None
---
apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: "tapms-webhook-server-cert"
spec:
  secretName: "tapms-webhook-server-cert"
  duration: 720h
  renewBefore: 24h
  organization:
    - Cray
  commonName: "tapms-webhook-service.cluster.svc"
  isCA: false
  keySize: 2048
  keyAlgorithm: rsa
  keyEncoding: pkcs1
  usages:
    - server auth
    - client auth
  dnsNames:
    - "tapms-webhook-service.tapms-operator.svc"
  issuerRef:
    name: cert-manager-issuer-common
    kind: Issuer
