/*
 *
 *  MIT License
 *
 *  (C) Copyright 2023 Hewlett Packard Enterprise Development LP
 *
 *  Permission is hereby granted, free of charge, to any person obtaining a
 *  copy of this software and associated documentation files (the "Software"),
 *  to deal in the Software without restriction, including without limitation
 *  the rights to use, copy, modify, merge, publish, distribute, sublicense,
 *  and/or sell copies of the Software, and to permit persons to whom the
 *  Software is furnished to do so, subject to the following conditions:
 *
 *  The above copyright notice and this permission notice shall be included
 *  in all copies or substantial portions of the Software.
 *
 *  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 *  IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 *  FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL
 *  THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR
 *  OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE,
 *  ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
 *  OTHER DEALINGS IN THE SOFTWARE.
 *
 */
// Package docs GENERATED BY SWAG; DO NOT EDIT
// This file was generated by swaggo/swag
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/v1alpha2/tenants": {
            "get": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Tenant and Partition Management System"
                ],
                "summary": "Get list of tenants' spec/status",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/Tenant"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/ResponseError"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/ResponseError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/ResponseError"
                        }
                    }
                }
            }
        },
        "/v1alpha2/tenants/{id}": {
            "get": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Tenant and Partition Management System"
                ],
                "summary": "Get a tenant's spec/status",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Either the Name or UUID of the Tenant",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/Tenant"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/ResponseError"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/ResponseError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/ResponseError"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "ResponseError": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string",
                    "example": "Error Message..."
                }
            }
        },
        "Tenant": {
            "description": "The primary schema/definition of a tenant",
            "type": "object",
            "required": [
                "spec"
            ],
            "properties": {
                "spec": {
                    "description": "The desired state of Tenant",
                    "$ref": "#/definitions/TenantSpec"
                },
                "status": {
                    "description": "The observed state of Tenant",
                    "$ref": "#/definitions/TenantStatus"
                }
            }
        },
        "TenantResource": {
            "description": "The desired resources for the Tenant",
            "type": "object",
            "required": [
                "type",
                "xnames"
            ],
            "properties": {
                "enforceexclusivehsmgroups": {
                    "type": "boolean"
                },
                "forcepoweroff": {
                    "type": "boolean"
                },
                "hsmgrouplabel": {
                    "type": "string",
                    "example": "green"
                },
                "hsmpartitionname": {
                    "type": "string",
                    "example": "blue"
                },
                "type": {
                    "type": "string",
                    "example": "compute"
                },
                "xnames": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    },
                    "example": [
                        "x0c3s5b0n0",
                        "x0c3s6b0n0"
                    ]
                }
            }
        },
        "TenantSpec": {
            "description": "The desired state of Tenant",
            "type": "object",
            "required": [
                "tenantname",
                "tenantresources"
            ],
            "properties": {
                "childnamespaces": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    },
                    "example": [
                        "vcluster-blue-slurm"
                    ]
                },
                "state": {
                    "type": "string",
                    "example": "New,Deploying,Deployed,Deleting"
                },
                "tenantname": {
                    "type": "string",
                    "example": "vcluster-blue"
                },
                "tenantresources": {
                    "description": "The desired resources for the Tenant",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/TenantResource"
                    }
                }
            }
        },
        "TenantStatus": {
            "description": "The observed state of Tenant",
            "type": "object",
            "properties": {
                "childnamespaces": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    },
                    "example": [
                        "vcluster-blue-slurm"
                    ]
                },
                "tenantresources": {
                    "description": "The desired resources for the Tenant",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/TenantResource"
                    }
                },
                "uuid": {
                    "type": "string",
                    "format": "uuid",
                    "example": "550e8400-e29b-41d4-a716-446655440000"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "v1alpha2",
	Host:             "cray-tapms",
	BasePath:         "/apis/tapms/",
	Schemes:          []string{},
	Title:            "TAPMS Tenant Status API",
	Description:      "Read-Only APIs to Retrieve Tenant Status",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
