//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright 2022.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha2

import (
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HsmComponent) DeepCopyInto(out *HsmComponent) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HsmComponent.
func (in *HsmComponent) DeepCopy() *HsmComponent {
	if in == nil {
		return nil
	}
	out := new(HsmComponent)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HsmComponentList) DeepCopyInto(out *HsmComponentList) {
	*out = *in
	if in.Components != nil {
		in, out := &in.Components, &out.Components
		*out = make([]HsmComponent, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HsmComponentList.
func (in *HsmComponentList) DeepCopy() *HsmComponentList {
	if in == nil {
		return nil
	}
	out := new(HsmComponentList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HsmGroup) DeepCopyInto(out *HsmGroup) {
	*out = *in
	if in.Tags != nil {
		in, out := &in.Tags, &out.Tags
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	in.Members.DeepCopyInto(&out.Members)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HsmGroup.
func (in *HsmGroup) DeepCopy() *HsmGroup {
	if in == nil {
		return nil
	}
	out := new(HsmGroup)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HsmIds) DeepCopyInto(out *HsmIds) {
	*out = *in
	if in.Ids != nil {
		in, out := &in.Ids, &out.Ids
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HsmIds.
func (in *HsmIds) DeepCopy() *HsmIds {
	if in == nil {
		return nil
	}
	out := new(HsmIds)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HsmMemberId) DeepCopyInto(out *HsmMemberId) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HsmMemberId.
func (in *HsmMemberId) DeepCopy() *HsmMemberId {
	if in == nil {
		return nil
	}
	out := new(HsmMemberId)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HsmPartition) DeepCopyInto(out *HsmPartition) {
	*out = *in
	if in.Tags != nil {
		in, out := &in.Tags, &out.Tags
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	in.Members.DeepCopyInto(&out.Members)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HsmPartition.
func (in *HsmPartition) DeepCopy() *HsmPartition {
	if in == nil {
		return nil
	}
	out := new(HsmPartition)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KeycloakGroup) DeepCopyInto(out *KeycloakGroup) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KeycloakGroup.
func (in *KeycloakGroup) DeepCopy() *KeycloakGroup {
	if in == nil {
		return nil
	}
	out := new(KeycloakGroup)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KeycloakRole) DeepCopyInto(out *KeycloakRole) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KeycloakRole.
func (in *KeycloakRole) DeepCopy() *KeycloakRole {
	if in == nil {
		return nil
	}
	out := new(KeycloakRole)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PowerStatus) DeepCopyInto(out *PowerStatus) {
	*out = *in
	if in.Status != nil {
		in, out := &in.Status, &out.Status
		*out = make([]XnamePowerState, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PowerStatus.
func (in *PowerStatus) DeepCopy() *PowerStatus {
	if in == nil {
		return nil
	}
	out := new(PowerStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PowerTransitionLocation) DeepCopyInto(out *PowerTransitionLocation) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PowerTransitionLocation.
func (in *PowerTransitionLocation) DeepCopy() *PowerTransitionLocation {
	if in == nil {
		return nil
	}
	out := new(PowerTransitionLocation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PowerTransitionRequest) DeepCopyInto(out *PowerTransitionRequest) {
	*out = *in
	if in.Location != nil {
		in, out := &in.Location, &out.Location
		*out = make([]PowerTransitionLocation, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PowerTransitionRequest.
func (in *PowerTransitionRequest) DeepCopy() *PowerTransitionRequest {
	if in == nil {
		return nil
	}
	out := new(PowerTransitionRequest)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PowerTransitionStartOutput) DeepCopyInto(out *PowerTransitionStartOutput) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PowerTransitionStartOutput.
func (in *PowerTransitionStartOutput) DeepCopy() *PowerTransitionStartOutput {
	if in == nil {
		return nil
	}
	out := new(PowerTransitionStartOutput)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Tenant) DeepCopyInto(out *Tenant) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Tenant.
func (in *Tenant) DeepCopy() *Tenant {
	if in == nil {
		return nil
	}
	out := new(Tenant)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Tenant) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TenantKmsResource) DeepCopyInto(out *TenantKmsResource) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TenantKmsResource.
func (in *TenantKmsResource) DeepCopy() *TenantKmsResource {
	if in == nil {
		return nil
	}
	out := new(TenantKmsResource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TenantKmsStatus) DeepCopyInto(out *TenantKmsStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TenantKmsStatus.
func (in *TenantKmsStatus) DeepCopy() *TenantKmsStatus {
	if in == nil {
		return nil
	}
	out := new(TenantKmsStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TenantList) DeepCopyInto(out *TenantList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Tenant, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TenantList.
func (in *TenantList) DeepCopy() *TenantList {
	if in == nil {
		return nil
	}
	out := new(TenantList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *TenantList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TenantResource) DeepCopyInto(out *TenantResource) {
	*out = *in
	if in.Xnames != nil {
		in, out := &in.Xnames, &out.Xnames
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TenantResource.
func (in *TenantResource) DeepCopy() *TenantResource {
	if in == nil {
		return nil
	}
	out := new(TenantResource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TenantSpec) DeepCopyInto(out *TenantSpec) {
	*out = *in
	if in.ChildNamespaces != nil {
		in, out := &in.ChildNamespaces, &out.ChildNamespaces
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.TenantResources != nil {
		in, out := &in.TenantResources, &out.TenantResources
		*out = make([]TenantResource, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	out.TenantKmsResource = in.TenantKmsResource
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TenantSpec.
func (in *TenantSpec) DeepCopy() *TenantSpec {
	if in == nil {
		return nil
	}
	out := new(TenantSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TenantStatus) DeepCopyInto(out *TenantStatus) {
	*out = *in
	if in.ChildNamespaces != nil {
		in, out := &in.ChildNamespaces, &out.ChildNamespaces
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.TenantResources != nil {
		in, out := &in.TenantResources, &out.TenantResources
		*out = make([]TenantResource, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	out.TenantKmsStatus = in.TenantKmsStatus
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TenantStatus.
func (in *TenantStatus) DeepCopy() *TenantStatus {
	if in == nil {
		return nil
	}
	out := new(TenantStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *XnamePowerState) DeepCopyInto(out *XnamePowerState) {
	*out = *in
	if in.SupportedPowerTransitions != nil {
		in, out := &in.SupportedPowerTransitions, &out.SupportedPowerTransitions
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new XnamePowerState.
func (in *XnamePowerState) DeepCopy() *XnamePowerState {
	if in == nil {
		return nil
	}
	out := new(XnamePowerState)
	in.DeepCopyInto(out)
	return out
}
